/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_1;


import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Polygon;
import java.awt.dnd.MouseDragGestureRecognizer;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Transform3D;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import javax.swing.TransferHandler;
import javax.swing.border.Border;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector3f;

/**
 *
 * @author Roan Thu
 */
public class GiaoDienChinh extends javax.swing.JFrame{

    /**
     * Creates new form GiaoDienChinh
     */
    public static VeDoThi graph;
    float size;
    double n;
    int xpoints[],ypoints[];
    private int map;
    private ImageIcon icon1, icon2;
    BufferedImage image1,image2;

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    public GiaoDienChinh() {
        initComponents();        
        
        jPanel1.setBackground(Color.lightGray);
        graph = new VeDoThi(0, 0);
        //graph.setBounds(jPanel1.getX(), jPanel1.getY(), jPanel1.getHeight(), jPanel1.getWidth());
        //jPanel1.setSize(1000, 700);
        graph.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel1.add(graph.canvas);
        n=0;
        jTextFieldSpan.setVisible(false);
        jLabelSpan.setVisible(false);
        Zoom();
        //jButton4.setIcon(icon1);
        //jButton5.setIcon(icon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonRefesh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButtonRack = new javax.swing.JToggleButton();
        jToggleButtonCrack = new javax.swing.JToggleButton();
        jToggleButtonPDU = new javax.swing.JToggleButton();
        jToggleButtonGrill = new javax.swing.JToggleButton();
        jToggleButtonAn = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelSpan = new javax.swing.JLabel();
        jTextFieldm = new javax.swing.JTextField();
        jButton2D = new javax.swing.JButton();
        typeGraph = new javax.swing.JComboBox<>();
        jTextFieldSpan = new javax.swing.JTextField();
        jTextField2D = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        endPoint = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonNguoiDuLich = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonDijsktra = new javax.swing.JButton();
        beginPoint = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vẽ Graph");

        jButtonRefesh.setText("Refesh");
        jButtonRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefeshActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1235, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        jToggleButtonRack.setText("RACK");
        jToggleButtonRack.setFocusable(false);
        jToggleButtonRack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonRack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonRack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRackActionPerformed(evt);
            }
        });

        jToggleButtonCrack.setText("CRAC");
        jToggleButtonCrack.setFocusable(false);
        jToggleButtonCrack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonCrack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonCrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCrackActionPerformed(evt);
            }
        });

        jToggleButtonPDU.setText("PDU");
        jToggleButtonPDU.setFocusable(false);
        jToggleButtonPDU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonPDU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonPDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPDUActionPerformed(evt);
            }
        });

        jToggleButtonGrill.setText("Grill");
        jToggleButtonGrill.setFocusable(false);
        jToggleButtonGrill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonGrill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonGrill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGrillActionPerformed(evt);
            }
        });

        jToggleButtonAn.setText("Ẩn cạnh");
        jToggleButtonAn.setFocusable(false);
        jToggleButtonAn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonAn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAnActionPerformed(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(153, 153, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSpan.setText("Span:");

        jButton2D.setText("Vẽ");
        jButton2D.setFocusable(false);
        jButton2D.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2D.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2DActionPerformed(evt);
            }
        });

        typeGraph.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mesh (m X n)", "2D (n X n)", "2D Torus (n X n)", "3D-cube", "4D-Cube", "5D-Cube", "6D-Cube", "layout", "Small World", "Fat tree (n port)", "Jellyfish" }));
        typeGraph.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        typeGraph.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeGraphItemStateChanged(evt);
            }
        });
        typeGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeGraphActionPerformed(evt);
            }
        });

        jLabel10.setText("N:");

        jLabel8.setText("Topo:");

        jLabel9.setText("M:");

        jLayeredPane1.setLayer(jLabelSpan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextFieldm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2D, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(typeGraph, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextFieldSpan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField2D, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeGraph, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabelSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(22, 22, 22)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2D, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jTextFieldm)
                            .addComponent(jTextFieldSpan))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2D)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpan))
                .addGap(18, 18, 18)
                .addComponent(jButton2D)
                .addContainerGap())
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Số đỉnh");

        jLabel2.setText("Số cạnh");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Vẽ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Dijsktra:");

        jLabel7.setText("Người du lịch:");

        jButtonNguoiDuLich.setText("Tìm");
        jButtonNguoiDuLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNguoiDuLichActionPerformed(evt);
            }
        });

        jLabel6.setText("Đỉnh cuối");

        jButtonDijsktra.setText("Tìm");
        jButtonDijsktra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDijsktraActionPerformed(evt);
            }
        });

        beginPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginPointActionPerformed(evt);
            }
        });

        jButton2.setText("Tìm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Các cạnh chứa đỉnh");

        jLabel5.setText("Đỉnh đầu");

        jLayeredPane3.setLayer(endPoint, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButtonNguoiDuLich, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButtonDijsktra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(beginPoint, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(beginPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNguoiDuLich))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDijsktra)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(beginPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDijsktra)
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNguoiDuLich)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem9.setText("New Design");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setText("Rack");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Crac");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("PDU");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenuView.setText("View");
        jMenuView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuViewMouseClicked(evt);
            }
        });

        jMenuItem4.setText("Top View");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItem4);

        jMenuItem5.setText("All View");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItem5);

        jMenuBar1.add(jMenuView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonRack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonCrack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonPDU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonGrill, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonAn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane3)
                            .addComponent(jLayeredPane1)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRefesh)
                        .addGap(16, 16, 16)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1235, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonRack)
                    .addComponent(jToggleButtonCrack)
                    .addComponent(jToggleButtonPDU)
                    .addComponent(jToggleButtonGrill)
                    .addComponent(jToggleButtonAn))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefesh))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    private int findIndex(String index){
        for(int i = 0; i < graph.data.getArrNut().size(); i++){
            if(graph.data.getArrNut().get(i).getIndex().equalsIgnoreCase(index))
                return i;
        }
        JOptionPane.showMessageDialog(null, "Không có đỉnh "+index);
        return -1;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
           int SoDinh = Integer.parseInt(jTextField1.getText());
           int SoCanh = Integer.parseInt(jTextField2.getText());
           if(SoCanh > (SoDinh)*(SoDinh-1)/2){
               JOptionPane.showMessageDialog(null, "Số cạnh quá lớn");
           }
           else{
           n = 0;
           jPanel1.remove(graph.canvas);
           jPanel1.setPreferredSize(new Dimension(1000, 700));
           graph = new VeDoThi(SoDinh, SoCanh);
           graph.setCursor(new Cursor(Cursor.HAND_CURSOR));
           jPanel1.add(graph.canvas);
           size = 5000f;
           stenable(true);
           repaint();
           }
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lỗi nhập");
        }
        Zoom();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int Dinh = findIndex(jTextField3.getText());
            if(Dinh >= 0){
            refresh();
            for(int i = 0; i < graph.data.getArrCanh().size(); i++){
                 
                int a = graph.data.getArrCanh().get(i).getIndexPointA();
                int b = graph.data.getArrCanh().get(i).getIndexPointB();
                if(a != Dinh && b != Dinh){
                    graph.data.getArrCanh().remove(i);
                    i--;
                }
            }
            graph.group1 = updateLine(graph);
            graph.transGroup.setChild(graph.group1, 1);
            jButtonRefesh.setEnabled(true);
            }     
    }//GEN-LAST:event_jButton2ActionPerformed
     public BranchGroup updateLine(VeDoThi graph) { // update location line after move point
        BranchGroup group = new BranchGroup();
        group.setCapability(BranchGroup.ALLOW_DETACH);
		for (int i = 0; i < graph.data.getArrCanh().size(); i++) {
                    int a = graph.data.getArrCanh().get(i).getIndexPointA();
                        int b = graph.data.getArrCanh().get(i).getIndexPointB();
                        int cost = graph.data.getArrCanh().get(i).getCost();
                        Color cor =graph.data.getArrCanh().get(i).getColorLine();
                    if(graph.data.getArrCanh().get(i) instanceof Line){
                        Canh e = new Line(graph.data.getArrNut().get(a).getP(), graph.data.getArrNut().get(b).getP(), a, b, cost,cor);
                        graph.data.getArrCanh().set(i, e);
                        e.creatLine(group);
                    }
                    else {
                        Canh e = new Canh2D(graph.data.getArrNut().get(a).getP(), graph.data.getArrNut().get(b).getP(), a, b, cost,cor);
                        graph.data.getArrCanh().set(i, e);
                        e.creatLine(group);
                     }
		}
                return group;
	}

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setSize(700, 600);
        int value = fc.showOpenDialog(this);
        if(value == JFileChooser.OPEN_DIALOG){
            String name = fc.getSelectedFile().getPath();
            try {
                n=0;
                jPanel1.remove(graph.canvas);
                graph=graph.readFile(name);
                
           graph.setCursor(new Cursor(Cursor.HAND_CURSOR));
           jPanel1.add(graph.canvas);
           size = 5000f;
           stenable(true);
           repaint();
                graph.setCursor(new Cursor(Cursor.HAND_CURSOR));
                jPanel1.add(graph.canvas);
                Zoom();
                stenable(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GiaoDienChinh.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser fc = new JFileChooser();
		fc.setDialogTitle("Save graph");
		int select = fc.showSaveDialog(this);
		if (select == 0) {
			String path = fc.getSelectedFile().getPath();  
			graph.writeFile(path);
		}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void refresh(){
        graph.data.setArrCanh(new ArrayList<>());
        for(int i = 0; i < graph.temparr.size(); i++){
            graph.data.getArrCanh().add(graph.temparr.get(i));
    }   
        graph.group1 = updateLine(graph);
        graph.transGroup.setChild(graph.group1, 1);
    }
    private void jButtonRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefeshActionPerformed
        refresh();
    }//GEN-LAST:event_jButtonRefeshActionPerformed

    private void beginPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beginPointActionPerformed

    private void jButtonDijsktraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDijsktraActionPerformed
            int begin = findIndex(beginPoint.getText());
            int end = -1;
            refresh();
            if(begin >= 0)
                end = findIndex(endPoint.getText());
            if(begin >= 0&&end >= 0){
                Dijsktra ds = new Dijsktra(graph, begin, end);
                repaint();
            }         
        
    }//GEN-LAST:event_jButtonDijsktraActionPerformed

    private void jButtonNguoiDuLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNguoiDuLichActionPerformed
        refresh();
        NguoiDuLich dl =new NguoiDuLich(graph);
        graph.repaint();
    }//GEN-LAST:event_jButtonNguoiDuLichActionPerformed

    private void jButton2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2DActionPerformed
        try {
           this.n = 0;
           int n = 0,m = 0, span = 0, Switch = 0 ;
           if(jTextField2D.isVisible())
           n = Integer.parseInt(jTextField2D.getText());
           if(jTextFieldm.isVisible())
           m = Integer.parseInt(jTextFieldm.getText());
           if(jTextFieldSpan.isVisible() == true)
           span = Integer.parseInt(jTextFieldSpan.getText());
           jPanel1.remove(graph.canvas);
           if(typeGraph.getSelectedIndex() == 0) graph = new VeDoThi(m, n, false);
           if(typeGraph.getSelectedIndex() == 1) graph = new VeDoThi(n, n, false);
           if(typeGraph.getSelectedIndex() == 2) graph = new VeDoThi(n, n, true);
           if(typeGraph.getSelectedIndex() == 3) graph = new VeDoThi(3, -0.15 ,0.15);
           if(typeGraph.getSelectedIndex() == 4) graph = new VeDoThi(4, 0.0 ,0.0);
           if(typeGraph.getSelectedIndex() == 5) graph = new VeDoThi(5, 0.0 ,0.0);
           if(typeGraph.getSelectedIndex() == 6) graph = new VeDoThi(6, 0.0 ,0.0);
           if(typeGraph.getSelectedIndex() == 9) graph = new VeDoThi(n);
           if(typeGraph.getSelectedIndex() == 10) graph = new VeDoThi(n,m, span, true);
           if(typeGraph.getSelectedIndex() == 7){
               BoTriMang botri = new BoTriMang(this);
               botri.setVisible(true);
           }
           if(typeGraph.getSelectedIndex() == 8){
               if(span < (m*n)*(m*n-1)/2-(2*m*n - m -n))
               graph = new VeDoThi(m, n, span);
               else JOptionPane.showMessageDialog(null, "Số span quá lớn");
           }
           //graph.setBounds(jPanel1.getX(), jPanel1.getY(), jPanel1.getHeight(), jPanel1.getWidth());
           graph.setCursor(new Cursor(Cursor.HAND_CURSOR));
           jPanel1.add(graph.canvas);
           size = 5000f;
           stenable(true);
           repaint();
           
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lỗi nhập");
        }
        Zoom();
    }//GEN-LAST:event_jButton2DActionPerformed

    private void typeGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeGraphActionPerformed
        if(typeGraph.getSelectedIndex() == 1||typeGraph.getSelectedIndex() == 2
                ||typeGraph.getSelectedIndex() == 9) {
              jTextField2D.setVisible(true);
              jTextFieldm.setVisible(false);
              jLabelSpan.setVisible(false);
              jTextFieldSpan.setVisible(false);
              jLabel10.setVisible(false);
              jLabel9.setText("N:");
              jLabel9.setVisible(true);
              
           }
         if(typeGraph.getSelectedIndex() == 0) {
            jTextField2D.setVisible(true);
            jTextFieldm.setVisible(true);
            jLabelSpan.setVisible(false);
            jTextFieldSpan.setVisible(false);
            jLabel9.setText("M:");
            jLabel10.setText("N:");
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
         }
          
         if(typeGraph.getSelectedIndex() == 3
              ||typeGraph.getSelectedIndex() == 4
              ||typeGraph.getSelectedIndex() == 5
              ||typeGraph.getSelectedIndex() == 6
              ||typeGraph.getSelectedIndex() == 7) {
              jTextField2D.setVisible(false);
              jTextFieldm.setVisible(false);
              jLabelSpan.setVisible(false);
              jTextFieldSpan.setVisible(false);
              jLabel9.setVisible(false);
              jLabel10.setVisible(false);
           }
         if(typeGraph.getSelectedIndex() == 8){
             jTextField2D.setVisible(true);
              jTextFieldm.setVisible(true);
              jLabel9.setText("M:");
              jLabel9.setVisible(true);
              jLabel10.setText("N:");
              jLabel10.setVisible(true);
              jLabelSpan.setText("Span:");
              jLabelSpan.setVisible(true);
              jTextFieldSpan.setVisible(true);
              
         }
         if(typeGraph.getSelectedIndex() == 10){
             jTextField2D.setVisible(true);
              jTextFieldm.setVisible(true);
              jLabel9.setText("Server:");
              jLabel9.setVisible(true);
              jLabel10.setText("Switch:");
              jLabel10.setVisible(true);
              jLabelSpan.setText("Port:");
              jLabelSpan.setVisible(true);
              jTextFieldSpan.setVisible(true);
         }
    }//GEN-LAST:event_typeGraphActionPerformed

    private void typeGraphItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeGraphItemStateChanged
        
    }//GEN-LAST:event_typeGraphItemStateChanged

    private void jMenuViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuViewMouseClicked
        
    }//GEN-LAST:event_jMenuViewMouseClicked

    private void jToggleButtonRackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRackActionPerformed
        if(jToggleButtonRack.isSelected()==true){
            graph.addRack = true;
            graph.addPDU=false;jToggleButtonPDU.setSelected(false);
            graph.addCrac=false;jToggleButtonCrack.setSelected(false);
            graph.addGrill=false;jToggleButtonGrill.setSelected(false);
        }
        else graph.addRack =false;
    }//GEN-LAST:event_jToggleButtonRackActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new DesignJFrame(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jToggleButtonCrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCrackActionPerformed
        if(jToggleButtonCrack.isSelected()==true){
            graph.addCrac=true;
            graph.addRack=false;jToggleButtonRack.setSelected(false);
            graph.addPDU=false;jToggleButtonPDU.setSelected(false);
            graph.addGrill=false;jToggleButtonGrill.setSelected(false);
        }
        else graph.addCrac =false;
    }//GEN-LAST:event_jToggleButtonCrackActionPerformed

    private void jToggleButtonPDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPDUActionPerformed
        if(jToggleButtonPDU.isSelected()==true){
            graph.addPDU=true;
            graph.addRack=false;jToggleButtonRack.setSelected(false);
            graph.addCrac=false;jToggleButtonCrack.setSelected(false);
            graph.addGrill=false;jToggleButtonGrill.setSelected(false);
        }
        else graph.addPDU =false;
    }//GEN-LAST:event_jToggleButtonPDUActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked
        
    }//GEN-LAST:event_jMenuItem5MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        graph.flagview = 0;
        graph.behavor.setEnable(false);
        Transform3D trans = new Transform3D();
        graph.transGroup.setTransform(trans);
        jToggleButtonCrack.setEnabled(true);jToggleButtonCrack.setSelected(false);
        jToggleButtonRack.setEnabled(true);jToggleButtonRack.setSelected(false);
        jToggleButtonPDU.setEnabled(true);jToggleButtonPDU.setSelected(false);
        jToggleButtonGrill.setEnabled(true);jToggleButtonGrill.setSelected(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        graph.flagview = 1;
        graph.behavor.setEnable(true);
        Transform3D trans = new Transform3D();
        trans.rotY(-Math.PI/6);
        Transform3D temp = new Transform3D();
        temp.rotX(-Math.PI/3);
        trans.mul(temp);
        graph.transGroup.setTransform(trans);
        jToggleButtonCrack.setEnabled(false);graph.addCrac=false;
        jToggleButtonRack.setEnabled(false);graph.addRack=false;
        jToggleButtonPDU.setEnabled(false);graph.addPDU=false;
        jToggleButtonGrill.setEnabled(false);graph.addGrill=false;
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jToggleButtonGrillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGrillActionPerformed
        if(jToggleButtonGrill.isSelected()==true){
            graph.addGrill=true;
            graph.addRack=false;jToggleButtonRack.setSelected(false);
            graph.addCrac=false;jToggleButtonCrack.setSelected(false);
            graph.addPDU=false;jToggleButtonPDU.setSelected(false);
        }
        else graph.addGrill =false;
    }//GEN-LAST:event_jToggleButtonGrillActionPerformed

    private void jToggleButtonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAnActionPerformed
        if(jToggleButtonAn.isSelected() == true){
            graph.data.setArrCanh(new ArrayList<>());
            graph.group1 = updateLine(graph);
            graph.transGroup.setChild(graph.group1, 1);
        }
        else refresh();
    }//GEN-LAST:event_jToggleButtonAnActionPerformed
    private int inArrCanh(int a, int b){
        for(int i = 0; i < graph.data.getArrCanh().size(); i++){
            int A = graph.data.getArrCanh().get(i).getIndexPointA();
            int B = graph.data.getArrCanh().get(i).getIndexPointB();
            if((a == A && b == B) || (a == B)&&(b == A)) return i;
        }
        return -1;
    }
    public void Zoom(){
        graph.canvas.addMouseWheelListener(new MouseWheelListener() {
            
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
               int no = e.getUnitsToScroll();
                n = n + no/4;
        graph.objtrans = graph.universe.getViewingPlatform().getViewPlatformTransform();
        graph.universe.getViewingPlatform().getViewPlatformTransform().getTransform(graph.trans);
        Vector3d temp = new Vector3d();
        graph.trans.get(temp);
        Vector3d translte = new Vector3d(temp.x, temp.y, 2.41+n/10);
        //System.out.println(2.41+n/100);
        Transform3D trans = new Transform3D();
        trans.setTranslation(translte);
        graph.objtrans.setTransform(trans);
        //graph.canvas.repaint();
        //simpleU.getViewingPlatform().setNominalViewingTransform();
        //simpleU.addBranchGraph(group);
            }
        });
    }  
    public void stenable(boolean what){
        jButton2.setEnabled(what);
        jTextField3.setEnabled(what);
        jButtonRefesh.setEnabled(what);
        beginPoint.setEnabled(what);
        endPoint.setEnabled(what);
        jButtonDijsktra.setEnabled(what);
        jButtonNguoiDuLich.setEnabled(what);
    }
    /**
     * @param args the command line arguments
     * 
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beginPoint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField endPoint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton2D;
    private javax.swing.JButton jButtonDijsktra;
    private javax.swing.JButton jButtonNguoiDuLich;
    private javax.swing.JButton jButtonRefesh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSpan;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField2D;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldSpan;
    private javax.swing.JTextField jTextFieldm;
    private javax.swing.JToggleButton jToggleButtonAn;
    private javax.swing.JToggleButton jToggleButtonCrack;
    private javax.swing.JToggleButton jToggleButtonGrill;
    private javax.swing.JToggleButton jToggleButtonPDU;
    private javax.swing.JToggleButton jToggleButtonRack;
    private javax.swing.JComboBox<String> typeGraph;
    // End of variables declaration//GEN-END:variables

}
